### ISSUE TITLE
The system show 0.0 basic salary for all employees

### ISSUE THREAD

**Issue by Alqupaty** [HIS-MOHAMMED/Airline-Management-System#32]
please check the method responsible for query the employees to fix a issue that makes the system show all employees basic salary is  **0.0**

**Comment by HIS-MOHAMMED** [comment]
Maybe I fixed the issue can you have a look if it's show the valid basic salary.

**Comment by HIS-MOHAMMED** [comment]
Maybe I fixed the issue can you have a look if it done please merge it to main stream.

**Comment by HIS-MOHAMMED** [comment]
Maybe I fixed the issue can you have a look if it done please merge it to main stream.

**Comment by Alqupaty** [comment]
Yaah it give a valid value now . Thanks

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the showAllEmployees method in EmployeesController.java to correctly display the basic salary of each employee. The issue was that the basic salary was not being retrieved from the Employee object.

You can review changes in this commit: https://github.com/lkilu6456546/HIS-MOHAMMED-Airline-Management-System-32/commit/29b7bc64414cfd0012f93b0d651dc6b0d8e2c764.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
